//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.23 at 02:06:06 PM UZT 
//


package edu.epam.fop.xml.jaxb.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="MessageType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SMS"/&gt;
 *     &lt;enumeration value="SMTP"/&gt;
 *     &lt;enumeration value="MMS"/&gt;
 *     &lt;enumeration value="MQTT"/&gt;
 *     &lt;enumeration value="AMQP"/&gt;
 *     &lt;enumeration value="DDS"/&gt;
 *     &lt;enumeration value="XMPP"/&gt;
 *     &lt;enumeration value="RCS"/&gt;
 *     &lt;enumeration value="IRC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MessageType")
@XmlEnum
public enum MessageType {

    SMS,
    SMTP,
    MMS,
    MQTT,
    AMQP,
    DDS,
    XMPP,
    RCS,
    IRC;

    public String value() {
        return name();
    }

    public static MessageType fromValue(String v) {
        return valueOf(v);
    }

}
