//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.23 at 02:06:06 PM UZT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.fop.epam.edu/messages")
package edu.epam.fop.xml.jaxb.model;
